import { getCssText } from "@/styles";
import { globalStyles } from "@/styles/global";
import type { Metadata } from "next";
import { Roboto } from "next/font/google";
import Image from "next/image";
import logoImg from "@/assets/logo.svg"
import { Container, Header } from "@/styles/pages/app";
import { CartProvider } from "@/context/CartContext";
import Modal from "@/components/cartModal";
globalStyles()

const roboto = Roboto({
  subsets: ['latin'], 
  weight: ['400', '700'], 
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt">
      <head>
          <style id="stitches" dangerouslySetInnerHTML={{__html: getCssText()}}></style>
      </head>
      <body className={`${roboto.className}`}>
        <CartProvider>
          <Container>
            <Header>
              <div>
                <Image src={logoImg} alt={"logo da loja"} priority/>
                <div>
                  <strong>Ignite</strong>
                  <span>shop</span>
                </div>
              </div>

              <Modal/>
            </Header>
            {children}
          </Container>
        </CartProvider>
      </body>
    </html>
  );
}
